#!/bin/bash
set -x
TEST_SETTINGS=etc/settings

echo Enable transparenct mode
# Mode 00 PCMND XRW_MODE0_GET_MODE Code 0x00 Config XRW_MODE0_GET_CONFIG
/opt/osdp-conformance/bin/open-osdp-kick ACU <${TEST_SETTINGS}/enable-transparent-mode.json

