# make file for documentation for transparent26

# assumes you have a working pandoc stack on the build machine...

PUBLISHED=transparent-mdoe-questions_20260508.pdf

all:	${PUBLISHED}

transparent-mdoe-questions_20260508.pdf:	research/transparent-mdoe-questions_20260508.md
	pandoc --toc -o transparent-mode-questions_20260508.pdf research/transparent-mode-questions_20260508.md

